@AccessControl.authorizationCheck: #NOT_REQUIRED
@EndUserText.label: 'Delivery Header Root View'
define root view entity ZR_DeliveryHeaderTp as select from ZI_DeliveryHeader
composition [1..*] of ZI_DeliveryItem as _item
{
    key Vbeln,
    Ernam,
    Erzet,
    Erdat,
    Bzirk,
    Vstel,
    Vkorg,
    Lfart,
    Autlf,
    Kzazu,
    Wadat,
    Lddat,
    Tddat,
    Lfdat,
    Kodat,
    Ablad,
    Inco1,
    Inco2,
    Expkz,
    Route,
    Vbtyp,
    Lprio,
    Vsbed,
    Btgew,
    Ntgew,
    Gewei,
    Volum,
    Voleh,
    Anzpk,
    Berot,
    Aedat,
    Bolnr,
    Xabln,
    WadatIst,
    CreatedBy,
    CreatedAt,
    LastChangedBy,
    LastChangedAt,
    _item // Make association public
}
